DROP TABLE IF EXISTS meals;

CREATE TABLE meals (
    id INTEGER NOT NULL AUTO_INCREMENT,
    meal_name VARCHAR(255) NOT NULL,
    category VARCHAR(80) NOT NULL,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS frequency;

CREATE TABLE frequency (
    id INTEGER NOT NULL AUTO_INCREMENT,
    times_used INTEGER,
    meal_id INT NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(meal_id) REFERENCES meals(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);